### ISSUE TITLE
GOAL: Persist the value to local storage

### ISSUE THREAD

**Issue by ecumene** [parrottjrs/think-write#6]
```js
const [value, setValue] = useState(localstorage.getItem("..."))

useEffect(() => {
  localstorage.setItem("...", value);
}, [value]);
```

**Comment by jackharrhy** [comment]
Sorry to lurk and nitpic, but this should probably be:
```js
const [value, setValue] = useState(() => localstorage.getItem("..."))
```
by passing a arrow function instead of just passing in the get item, it will only call the function _once_ on initial render of the component, not attempt to run getItem _every_ time the component renders, even though this is only used to seed useState and isn't useful after the first render

see https://react.dev/reference/react/useState#parameters
